name: Ngx-Storage tests

on:
  push:
    branches: [master, ng-v*]
  pull_request:
    branches: [master, ng-v*]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run lint
      - run: npm run ci:test
